export { default as Home } from '@/src/components/view/Home'
export { default as Exchanges } from '@/src/components/view/Exchanges'
export { default as WatchList } from '@/src/components/view/WatchList'
export { default as Cryptocurrencies } from '@/src/components/view/Cryptocurrencies'
export { default as Crypto } from '@/src/components/view/Crypto'